const ActionTypes = {
  
    // User
    SET_PROFILE_BY_LOGIN: "USER/SET_PROFILE_BY_LOGIN",
    LOGOUT: "LOGOUT",

    // Currencies
    SET_DASH_CARD_PRICES: "CURRENCIES/SET_DASH_CARD_PRICES",

    // Offers
    SET_LAST_TXS: "OFFERS/SET_LAST_TXS",
    SET_LAST_DEFAULT_TXS: "OFFERS/SET_LAST_DEFAULT_TXS",
    SET_ACTIVE_OFFERS: "OFFERS/SET_ACTIVE_OFFERS",
    SET_USER_ACTIVE_OFFERS: "OFFERS/SET_USER_ACTIVE_OFFERS",

    // Wallet
    SET_USER_WALLET: "WALLET/SET_USER_WALLET",

    // Tickets
    SET_USER_TICKETS: "TICKETS/SET_USER_TICKETS"
};

export default ActionTypes;
